[tool.poetry]
name = "elspot2mqtt"
version = "0.3.0"
description = ""
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.dependencies]
python = "^3.9"
pip = "^21.0.1"
requests = "^2.25.1"
nordpool = "^0.3.1"
paho-mqtt = "^1.5.1"
dataclasses-json = "^0.5.2"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]
black = "^22"
isort = "^5"
pylama = "8.4.1"
pytest = "^7.1.3"
pytest-black = "^0.3.12"
pytest-isort = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
elspot2mqtt = "elspot2mqtt.cli:main"
