[tool.poetry]
name = "elspot2mqtt"
version = "0.6.0"
description = "Elspot to MQTT Integration"
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
nordpool = "^0.3.3"
paho-mqtt = "^1.6.1"
dataclasses-json = "^0.6.1"
pandas = "^2.1.1"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
pytest = "^7.1.3"
pytest-black = "^0.3.12"
pytest-isort = "^3.0.0"
pylama = "^8.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
elspot2mqtt = "elspot2mqtt.cli:main"

[tool.isort]
profile = "black"

[tool.pylama]
ignore = "E203"

[tool.pylama.linter.pycodestyle]
max_line_length = 120

[tool.pylama.linter.mccabe]
complexity = 40
