[tool.poetry]
name = "elspot2mqtt"
version = "0.7.0"
description = "Elspot to MQTT Integration"
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
#nordpool = ">=0.4.1"
nordpool = {git = "https://github.com/kipe/nordpool.git", rev = "main"}
paho-mqtt = "^1.6.1"
pandas = "^2.1.1"
pydantic = "^2.7.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
pytest-isort = "^3.0.0"
ruff = "^0.4.4"

pytest = "^8.2.0"
pytest-ruff = "^0.3.2"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
elspot2mqtt = "elspot2mqtt.cli:main"

[tool.isort]
profile = "black"

[tool.pylama]
ignore = "E203"

[tool.pylama.linter.pycodestyle]
max_line_length = 120

[tool.pylama.linter.mccabe]
complexity = 40
