[tool.poetry]
name = "elspot2mqtt"
version = "0.1.0"
description = ""
authors = ["Jakob Schlyter <jakob@kirei.se>"]

[tool.poetry.dependencies]
python = "^3.9"
pip = "^21.0.1"
requests = "^2.25.1"
nordpool = "^0.3.1"
paho-mqtt = "^1.5.1"
dataclasses-json = "^0.5.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
pylama = "^7.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
elspot2mqtt = "elspot2mqtt:main"
