name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        python-version: "3.13"
        enable-cache: true
    - name: Run pytest
      run: uv run pytest --ruff --ruff-format
