name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install and set up Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: poetry install
    - name: Run pytest
      run: poetry run pytest --black --isort --pylama
    - name: Execute
      run: poetry run elspot2mqtt --help
